[versions]
javapoet = "1.13.0"
targetSdk = "34"
compileSdk = "34"
kotlinJvmTarget = "17"
kotlin = "1.9.20"
agp = "8.3.0"
ksp = "1.9.20-1.0.14"
coroutines = "1.7.3"
androidxActivity = "1.8.2"
androidxFragment = "1.6.2"
androidxCore = "1.12.0"
androidxArchCore = "2.1.0"
androidxLifecycle = "2.7.0"
androidxSavedState = "1.2.1"
androidxViewPager2 = "1.0.0"
androidxWebkit = "1.6.0"
androidxCoordinatorlayout = "1.1.0"
drawerLayout = "1.1.1"
appCompat = "1.6.1"
cardView = "1.0.0"
material = "1.11.0"
swipeRefreshLayout = "1.1.0"
androidXAnnotation = "1.1.0"
recyclerView = "1.2.1"
gridLayout = "1.0.0"
constraintLayout = "2.1.4"
navigation = "2.7.7"
splashScreen = "1.0.1"
dataStore = "1.0.0"
rxJava2 = "2.2.19"
rxKotlin2 = "2.4.0"
rxJava2Extensions = "0.20.8"
rxJavaProGuardRules = "1.1.6.0"
rxAndroid2 = "2.1.1"
rxRelay2 = "2.1.1"
rxReplayingShare = "2.2.0"
groupie = "2.10.1"
timber = "4.7.1"
retrofit = "2.9.0"
coil = "2.6.0"
eithernet = "1.2.1"
dagger = "2.51"
jsr305 = "3.0.1"
okHttp = "5.0.0-alpha.12"
okio = "3.7.0"
moshi = "1.15.0"
moshiX = "0.17.0"
junit = "4.13.2"
kluent = "1.61"
robolectric = "4.9.2"
espresso = "3.5.1"
androidxTest = "1.5.0"
androidxTestExt = "1.1.5"
turbine = "1.0.0"
jetbrainsKotlinJvm = "1.9.0"
activity = "1.8.0"
gson = "2.10.1"

[libraries]
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-savedstate-ktx = { group = "androidx.savedstate", name = "savedstate-ktx", version.ref = "androidxSavedState" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraint-layout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintLayout" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger" }
dagger-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger" }
dagger-android = { group = "com.google.dagger", name = "dagger-android", version.ref = "dagger" }
dagger-android-compiler = { group = "com.google.dagger", name = "dagger-android-processor", version.ref = "dagger" }
dagger-android-support = { group = "com.google.dagger", name = "dagger-android-support", version.ref = "dagger" }

retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit2-moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
retrofit2-eithernet = { group = "com.slack.eithernet", name = "eithernet", version.ref = "eithernet" }
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okHttp" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
moshi-kotlin-codegen = { group = "com.squareup.moshi", name = "moshi-kotlin-codegen", version.ref = "moshi" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kluent = { group = "org.amshove.kluent", name = "kluent", version.ref = "kluent" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTest" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExt" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
groupie = { group = "com.github.lisawray.groupie", name = "groupie", version.ref = "groupie" }
groupie-viewbinding = { group = "com.github.lisawray.groupie", name = "groupie-viewbinding", version.ref = "groupie" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsKotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }

